### ISSUE TITLE
IncompatibleClassChangeError with Javassist instrumented classes

### ISSUE THREAD

**Issue by henri-tremblay** [easymock/easymock#157]
*Migrated from:* CodeHaus issue EASYMOCK-146
*Original reporter:* Petras Petkus

---------------------------------------------------------
I have Hibernate JPA entities, bytecode instrumented with Javassist using Ant task {{org.hibernate.tool.instrument.javassist.InstrumentTask}} (see: [Hibernate bytecode instrumentation|http://docs.jboss.org/hibernate/orm/4.3/manual/en-US/html_single/#performance-fetching-lazyproperties] for lazy property fetching). With v3.3.1 EasyMock crashes with this exception when creating mock on entity class:
bq. java.lang.IncompatibleClassChangeError: class net.sf.cglib.core.DebuggingClassWriter has interface org.objectweb.asm.ClassVisitor as super class

Previous EasyMock v3.3 version works with instrumented classes and successfully creates mocks with their classes.
I attached the stacktrace.

---------------------------------------------------------
See https://github.com/henri-tremblay/easymock-issue-attachments/blob/master/IncompatibleClassChangeError.txt

**Comment by henri-tremblay** [comment]
*Original comment author:* Henri Tremblay

---------------------------------------------------------
I should have answered that way sooner. I think the problem comes from ASM or cglib. EasyMock is using the latest version but they probably mismatch with some libraries you are using.

Please try to upgrade everything and tell me how it goes. These versions are necessary to be compliant with Java 8.

**Comment by henri-tremblay** [comment]
*Original comment author:* Petras Petkus

---------------------------------------------------------
Dear Henri,

Thank you for your message. Following your advice I checked my project deppendencies and found that Apache CXF Runtime JAX WS Frontend (artifactId "cxf-rt-frontend-jaxws") we use has dependency on old version of ASM v3.3.1. It seems it is not required for runtime. When excluded no more exception occur and mocking with EasyMock v3.3.1 works. Thank you very much.

**Comment by henri-tremblay** [comment]
*Original comment author:* Henri Tremblay

---------------------------------------------------------
The issue is now solved. However, I'll leave the door open to provide a version that can't clash with other dependencies.

**Comment by mlippens** [comment]
I've had the exact same message with Spock. Any idea what exactly causes this?
