### ISSUE TITLE
Incomplete sentence in documentation

### ISSUE THREAD

**Issue by justinjhendrick** [easymock/easymock#163]
On the getting started page, 
"We are testing here that `documentAdded` will be called once and only once using this exact parameter. That's what we expect. Any other result means "

Any other result means what?

https://github.com/easymock/easymock/blob/master/website/getting-started.html#L86

**Comment by henri-tremblay** [comment]
It should read "Any other result means that the collaborator is notified too many times (or not at all)"

Thanks for the feedback!
