### ISSUE TITLE
EasyMock.anyInt() mock Integer fail

### ISSUE THREAD

**Issue by ljw1q2w** [easymock/easymock#177]
appInfoMapper.countAppByTypeId(Integer param);
mock:
1.EasyMock.expect(appInfoMapper.countAppByTypeId(EasyMock.anyInt())).andReturn(12);
exception:
java.lang.AssertionError: 
  Unexpected method call AppInfoMapper.countAppByTypeId(0):
2.EasyMock.expect(appInfoMapper.countAppByTypeId(EasyMock.anyObject(Integer.class))).andReturn(12);
exception:
java.lang.AssertionError: 
  Unexpected method call AppInfoMapper.countAppByTypeId(null):

how to resolve this issue?

**Comment by henri-tremblay** [comment]
I would need a full test case to help you.
My guess is that you are mixing primitive and class types (int and Integer). 
But this is usually allowed. For instance, this is working perfectly:

```
public class AppInfoTest {

    public interface AppInfoMapper {
        int countAppByTypeId(Integer i);
    }

    @Test
    public void test() {
        AppInfoMapper appInfoMapper = createMock(AppInfoMapper.class);
        expect(appInfoMapper.countAppByTypeId(EasyMock.anyInt())).andReturn(12);

        replay(appInfoMapper);

        assertEquals(12, appInfoMapper.countAppByTypeId(new Integer(0)));
    }
}
```

**Comment by ljw1q2w** [comment]
Thank you for your answer patiently,
 This issue has been resloved, because i put  replay(appInfoMapper) before expect . I'm sorry to disturb you.
Good luck.

**Comment by Koi7** [comment]
Issue is not resolved as if you are using MockType.Nice it will return null for Integer type and you get NPE for anyObject and anyInt.

**Comment by henri-tremblay** [comment]
@Koi7 Can you provide a fully working test case showing the issue?
