### ISSUE TITLE
Semantic Versioning 

### ISSUE THREAD

**Issue by stokito** [easymock/easymock#179]
Hi,
Easymock artifacts are not fully following with [SemVer](http://semver.org/) because a PATCH section is omitted (i.e. 3.4 but should be 3.4.0).
Actually that is legal for Maven but not for standard. That's why in [VersionEye](https://www.versioneye.com/java/org.easymock:easymock/3.4) the EasyMock artifact has a warning.

**Comment by henri-tremblay** [comment]
I'm not convinced here... JUnit and Hamcrest are not following this rule either. Why should it be the ultimate rule?

**Comment by stokito** [comment]
According to semver spec:
> A normal version number MUST take the form X.Y.Z

MUST   This word, or the terms "REQUIRED" or "SHALL", mean that the
   definition is an absolute requirement of the specification.

For me that's issue in spec and it's better to change spec than everybody's projects. 
In SemVer tracker there is [long discussion about this](https://github.com/mojombo/semver/issues/237)
But it's simpler and better to do than discuss.

**Comment by henri-tremblay** [comment]
Will close that. I don't care about semver spec.
