### ISSUE TITLE
Wrong expected Throwable, but the test passes

### ISSUE THREAD

**Issue by jferard** [easymock/easymock#187]
This test should fail, but it does not:
```
@Test
public final void testShouldFail() {
	Logger logger = EasyMock.createStrictMock(Logger.class);

	logger.log(EasyMock.eq(Level.SEVERE), EasyMock.eq("message"),
			EasyMock.anyObject(IllegalArgumentException.class));

	EasyMock.replay(logger);
	// not really the expected call
	logger.log(Level.SEVERE, "message", new SQLException());
	EasyMock.verify(logger);
}
```
It should fail because an ```SQLException``` is *not* an ```IllegalArgumentException```.

Java 1.8, JUnit 4.12, EasyMock 3.4. For a minimal project that shows the issue, see https://com.github/jferard/easymockissue

**Comment by tammofreese** [comment]
Sorry for the confusion, `anyObject(…)` allows any object. You can pass a class because there were situations in which the compiler requires the class for the return type.

If you would like to check the type, try `isA(…)` instead.

**Comment by jferard** [comment]
Oh, sorry. I just read the doc more carefully. It's a mistake I have been making for a long time... Thank you, I close the issue.

**Comment by tammofreese** [comment]
@jferard no worries, glad it works for you now!
