### ISSUE TITLE
Delay the response of a stub.

### ISSUE THREAD

**Issue by kanuku** [easymock/easymock#188]
It would be great if we could delay a stub to i.e.: simulate timeouts.

```java
client.call(url);
expectLastCall().andWait(35000); //35 seconds

```

**Comment by henri-tremblay** [comment]
I don't think I will add that since it feels like something that is quite rare to need. And it is already possible by doing something like

```java
expectLastCall().andAnswer(() -> {
  try { Thread.sleep(35000); } catch(InteruptedException e) {}
  return null;
});
```

**Comment by fliaping** [comment]
I think it's useful when testing timeout and retry

**Comment by henri-tremblay** [comment]
@fliaping As mentioned in my answer, there is an easy workaround. I'm reluctant to add code and a dedicated method for such a niche issue. With a perfect workaround.
