### ISSUE TITLE
Easymock does not work with Java 9 b148+

### ISSUE THREAD

**Issue by uschindler** [easymock/easymock#193]
It is no longer possible to inject classes into foreign ClassLoaders by making `ClassLoader#defineClass()` accessible. This breaks CGLIB, that is used by EasyMock. The corresponding issue is https://github.com/cglib/cglib/issues/93. To inject classes into foreign ClassLoaders you have to use `sun.misc.Unsafe#defineClass()`, because Java 9 has a special case for legacy code, so you can still get a "deprecated backwards-compatibility Unsafe" (Java 9 internally uses another Unsafe).

See issue: https://issues.apache.org/jira/browse/SOLR-9893

**Comment by uschindler** [comment]
Example stack trace (using Easymock 3.4 + Java 9 EA build 152):

```
   [junit4]    > Throwable #1: java.lang.ExceptionInInitializerError
   [junit4]    >        at __randomizedtesting.SeedInfo.seed([AC6240241F854C7:5B230C2B8AB54ED7]:0)
   [junit4]    >        at org.easymock.cglib.core.KeyFactory$Generator.generateClass(KeyFactory.java:166)
   [junit4]    >        at org.easymock.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
   [junit4]    >        at org.easymock.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:216)
   [junit4]    >        at org.easymock.cglib.core.KeyFactory$Generator.create(KeyFactory.java:144)
   [junit4]    >        at org.easymock.cglib.core.KeyFactory.create(KeyFactory.java:116)
   [junit4]    >        at org.easymock.cglib.core.KeyFactory.create(KeyFactory.java:108)
   [junit4]    >        at org.easymock.cglib.core.KeyFactory.create(KeyFactory.java:104)
   [junit4]    >        at org.easymock.cglib.proxy.Enhancer.<clinit>(Enhancer.java:69)
   [junit4]    >        at org.easymock.internal.ClassProxyFactory.createEnhancer(ClassProxyFactory.java:257)
   [junit4]    >        at org.easymock.internal.ClassProxyFactory.createProxy(ClassProxyFactory.java:165)
   [junit4]    >        at org.easymock.internal.MocksControl.createMock(MocksControl.java:113)
   [junit4]    >        at org.easymock.internal.MocksControl.createMock(MocksControl.java:94)
   [junit4]    >        at org.easymock.EasyMock.mock(EasyMock.java:69)
   [junit4]    >        at org.easymock.EasyMock.createMock(EasyMock.java:311)
   [junit4]    >        at org.apache.solr.core.CoreSorterTest.getMockContainer(CoreSorterTest.java:107)
   [junit4]    >        at org.apache.solr.core.CoreSorterTest.testSort(CoreSorterTest.java:87)
   [junit4]    >        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   [junit4]    >        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   [junit4]    >        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   [junit4]    >        at java.base/java.lang.reflect.Method.invoke(Method.java:543)
   [junit4]    >        at java.base/java.lang.Thread.run(Thread.java:844)
   [junit4]    > Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @3cfab390
   [junit4]    >        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:207)
   [junit4]    >        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:192)
   [junit4]    >        at java.base/java.lang.reflect.Method.setAccessible(Method.java:186)
   [junit4]    >        at org.easymock.cglib.core.ReflectUtils$2.run(ReflectUtils.java:56)
   [junit4]    >        at java.base/java.security.AccessController.doPrivileged(Native Method)
   [junit4]    >        at org.easymock.cglib.core.ReflectUtils.<clinit>(ReflectUtils.java:46)
   [junit4]    >        ... 54 more
```

**Comment by henri-tremblay** [comment]
Thanks for reporting. I will do a release a soon a cglib is released

**Comment by uschindler** [comment]
I hope this happens soon. Maybe you can ping them, too.

Uwe

**Comment by ajrepp** [comment]
It looks like the cglib update has happened -- https://github.com/cglib/cglib/releases/tag/RELEASE_3_2_5 was released in March. @henri-tremblay do you think we can get easymock updated?

**Comment by henri-tremblay** [comment]
Yes. I'm a bit overloaded these days. But I want to do it soon. Anyone wants to help?

**Comment by ijuma** [comment]
I submitted https://github.com/easymock/easymock/pull/200 that simply updates the dependencies and the tests pass.

**Comment by ijuma** [comment]
A new release of easymock would be helpful. Any idea when this may happen @henri-tremblay?

**Comment by henri-tremblay** [comment]
I have one more thing on my plate and can do it after. So soon. Sorry for the delay

**Comment by ijuma** [comment]
Thanks for the update. That's good to hear. :) No worries about the delay, I totally understand. The reason why I was asking is that the next Kafka release is happing in September and I'd like to claim Java 9 support. Once we upgrade to the new EasyMock version, we can have a CI build for Java 9 that runs most of the tests (a small number of PowerMock tests would be excluded).

**Comment by henri-tremblay** [comment]
Ok. I'll try to make it quick then

**Comment by ijuma** [comment]
Thanks for releasing 3.5. :)

**Comment by henri-tremblay** [comment]
You're welcome. Please tell me if everything is alright

**Comment by ijuma** [comment]
Yes, all good. A couple of tests had to be modified, but the tests were at fault (seems like the verification of the updated version is stricter in some cases).

**Comment by henri-tremblay** [comment]
Yes. As mentioned in the release notes, we are now checking the for unexpected calls. Normally it's not necessary because you should get an AssertionError before verification. But in some cases, the assertion is swallowed. Especially when multithreading. In general, this is what you want but it is indeed stricter.

**Comment by ijuma** [comment]
Yes, I agree it's an improvement.
