### ISSUE TITLE
API changes report for EasyMock

### ISSUE THREAD

**Issue by lvc** [easymock/easymock#204]
Hi,

I'd like to share my results on API changes analysis of the library: https://abi-laboratory.pro/java/tracker/timeline/easymock/

The report is generated by the https://github.com/lvc/japi-compliance-checker tool for jars found at http://central.maven.org/maven2/org/easymock/easymock/ according to https://wiki.eclipse.org/Evolving_Java-based_APIs_2.

Thank you.

![easymock-2](https://user-images.githubusercontent.com/1517837/31161299-b7dc265c-a8de-11e7-9be7-8aa93c8150df.png)
![easymock-1](https://user-images.githubusercontent.com/1517837/31161300-b7f86560-a8de-11e7-8c50-8bcdfcb34bbc.png)

**Comment by henri-tremblay** [comment]
Thanks. I think everything was expected. How can we know which methods were added or removed?

**Comment by lvc** [comment]
> How can we know which methods were added or removed?

Go to https://abi-laboratory.pro/java/tracker/timeline/easymock/ and click on table cells to view report details.

Thank you.

**Comment by henri-tremblay** [comment]
Yes. Sorry. Saw that after
