### ISSUE TITLE
Ant dependency is incorrectly packaged into easymock:jar:3.5

### ISSUE THREAD

**Issue by stokito** [easymock/easymock#205]
After update from v3.4 to v3.5 my build was failed because maven-enforcer-plugin detected that now we have duplicated classes in classpath:
```
Duplicate classes found:

  Found in:
    ant:ant:jar:1.6.5:test
    org.easymock:easymock:jar:3.5:test
  Duplicate classes:
    org/apache/tools/ant/taskdefs/WhichResource.class
    org/apache/tools/ant/types/selectors/PresentSelector.class
    org/apache/tools/ant/taskdefs/Touch$DateFormatFactory.class
    org/apache/tools/ant/helper/DefaultExecutor.class
...
```

All other dependencies of EM was repackaged into org.easymock.cglib or org.easymock.asm

Could you repackage ant under org.easymock package?
Or could you remove ant dep at all? Or at least provide an EM artifact without embedded deps?

**Comment by henri-tremblay** [comment]
Arg! Thanks for reporting. It seems to come from cglib 3.5. I will fix it ASAP. It should definitely not be there.

**Comment by stokito** [comment]
Hi again, I don't know if I should create another ticket but now I see that testng is also included into easymock.
My college accidentally imported some assert from testng via IntelliJ suggestion and broke a build. Can you also exclude testng?
Thank you.
