### ISSUE TITLE
Getting Started Example returns NullPointerException

### ISSUE THREAD

**Issue by jessewriter** [easymock/easymock#215]
In order for me to get the 'Getting Started Example' to work I had to make these changes to the examples.

` @Mock 
	    private Collaborator collaborator = mock(Collaborator.class); // 1`
As you can see I had to add **=mock(Collaborator.class)** otherwise calling collaborator returns a NPE.

// UPDATE this issue affects jUnit5 not jUnit4

ClassUnderTest was also incomplete.  See updated code to make project work

`	  public void addDocument(String title, String document) {
listener.documentAdded(title);
	  }`

added: **listener.documentAdded(title);**

**Comment by henri-tremblay** [comment]
You do not need to. The `@Rule` will assign the mock to the collaborator. Can you give me the full code to see what's wrong?

But you are right about `addDocument`. I will fix it.

**Comment by jessewriter** [comment]
I found out this issue is isolated to jUnit5 even with the @Rule.  switching back to jUnit4 and it works just as you posted.

**Comment by henri-tremblay** [comment]
Ah! JUnit 5! Yes. I don't think it supports rules. And I haven't tested with JUnit 5 yet. It seems to require Extensions. You can file an issue for that.
