### ISSUE TITLE
Serve easymock.org over HTTPS

### ISSUE THREAD

**Issue by einsteinsfool** [easymock/easymock#220]
HTTP websites are vulnerable to MITM attacks. Someone can switch the content of the website on the client side that runs a malicious script, displays porn ads or even changes links to malicious files.

It would be cool if `easymock.org` was served over HTTPS, preferably with HSTS (which is a header that forces to use HTTPS even if someone goes to HTTP version of a page). This can be added for free e.g. by using **Let's Encrypt**.

As for implementing HSTS, [this](https://www.globalsign.com/en/blog/what-is-hsts-and-how-do-i-use-it) might be worth reading.

**Comment by henri-tremblay** [comment]
Done. Github now supports HTTPS for custom domains.
