### ISSUE TITLE
Mocking void methods are not threadsafe unless you explicitly use `replay`

### ISSUE THREAD

**Issue by bobyangyf** [easymock/easymock#222]
If you create a mock with `EasyMock.createMock(Foo.class)`, where `void bar()` exists as part of `Foo`, and then use the mock object directly without calls to `replay`, the `Foo.bar()` method will not be threadsafe.

Attached a demo.

[EasyMockDemo.zip](https://github.com/easymock/easymock/files/2225091/EasyMockDemo.zip)

**Comment by henri-tremblay** [comment]
Yes. But you do need to call replay before using the mock. 

And indeed, EasyMock is threadsafe on replay only. Not during the recording phase.

**Comment by bobyangyf** [comment]
I suppose there is no explicit recording / using phase that can enforce the user of `replay` either.
This is a frequent/easy to encounter bug due to this. I think it would be helpful to explicitly document the lack of theadsafety during recording.

**Comment by henri-tremblay** [comment]
See the multithreading chapter of the [user guide](http://easymock.org/user-guide.html)

**Comment by bobyangyf** [comment]
Cool. Thanks.
