### ISSUE TITLE
Java 11 Compatibility check: EasyMock

### ISSUE THREAD

**Issue by KryniuPL** [easymock/easymock#224]
Hi,
We are reaching out to you to check Java 11 compatibility of the library EasyMock.

Could you help us by answering the following questions:

1. Library Name: <library name.="" e.g:="" activation="">
2. Latest version: <latest 1.1.1="" eg:="" version.="">
3. Latest version Is the library compatible with Java 11 Compatible? (Y/N)
4. Is the library supported with Java 11? (Y/N)
5. (If “N” in compatibility or support) What is the versions that would be compatible and Supported?
6. Date of support availability?</latest></library>

Appreciate your response by 19.08.2018.

Thanks,
Krzysztof Dragan,
PTC Inc. Contractor

**Comment by ijuma** [comment]
I'm just a user, but EasyMock has partial support for Java 11 in master. For full support, it needs a cglib release with the following:

https://github.com/cglib/cglib/pull/131

Then users can set the appropriate property to be able to mock classes with Java 11 bytecode.

**Comment by henri-tremblay** [comment]
Thanks @ijuma. I will try to release this will to fix this (finally might have some time).

**Comment by burkti** [comment]
Hi all, is there any schedule available when an EasyMock release for Java 11 will be available? Thank you!

**Comment by henri-tremblay** [comment]
September. I am currently underwater but should get out in about a week.

**Comment by ijuma** [comment]
If we merge https://github.com/easymock/easymock/pull/225, then we can release a new version of EasyMock that works with Java 11.

**Comment by ijuma** [comment]
@henri-tremblay Are we any closer here? :)

**Comment by KryniuPL** [comment]
Can anyone comment on dependencies of **objenesis** library in new version of EasyMock ?

**Comment by ijuma** [comment]
FYI, Java 11 has been released https://mail.openjdk.java.net/pipermail/announce/2018-September/000257.html

**Comment by davidkarlsen** [comment]
All set for release?

**Comment by henri-tremblay** [comment]
No. To give you a heads up, I need to fix the usage of Unsafe.defineClass in Objenesis. It is a known problem already fixed in other frameworks. So it won't take long. When I'm done, I will deliver it and then deliver EasyMock.

**Comment by przemekwolski8** [comment]
> Seems like we're close :) [d1b032c](https://github.com/easymock/easymock/commit/d1b032c50f91421ac5a6b457873dc7c0c1d83e9f)

Yes, but still using JDK internal API :)

**Comment by henri-tremblay** [comment]
@przemekwolski8 Yes. Since 2003. You can't do magical things without it. Unless they add Unsafe.allocateInstance to the JDK. I'm all for it.

**Comment by henri-tremblay** [comment]
No. It will be 4.0. Not much changes though. So no need to worry I think. I'm just dropping  > 1.8 support. Since Objenesis also dropped it. I hope it's not a problem for you.
