### ISSUE TITLE
No simple way to verify non void method call.

### ISSUE THREAD

**Issue by Koi7** [easymock/easymock#236]
Hi. I have following case: i want just to verify that some non-void method X being called N times and that is all i want. I do not want to record any return value for this method. I just want something similar to void methods:
```
foo.X();
expectLastCall().once();
```
So how do i achieve that? Is it even possible? 
p.s.: for now I record state like this:

`expect(foo.X()).andReturn(someMock).once();`

**Comment by henri-tremblay** [comment]
Please, do not create issues to ask questions. Use stackoverflow or gitter.

To verify a call, you need to record it. That's how EasyMock works right now (it might change in the future with some contributors help).

The code would be:

```java
expect(foo.X()).andReturn(someMock).times(5);
replay(foo);
// ... do the test doing the calls ...
verify(foo); // verify that all expected calls were done
