### ISSUE TITLE
No need to have two generic parameters on EasyMock.createMock

### ISSUE THREAD

**Issue by henri-tremblay** [easymock/easymock#237]
Now that we return a different type than the requested type to mock `public static <T, R> R mock(String name, Class<T> toMock)`.

But this is actually not necessary and changed the type. So if someone was using a type witness, the code won't compile anymore.

The solution is to remove the return type to have `public static <T> T mock(String name, Class<?> toMock)` which is equivalent but compatible.

**Comment by ijuma** [comment]
Is there really no relation between `toMock` and the return type?

**Comment by henri-tremblay** [comment]
There is. But generics won't allow a valid typing. I would be (really) happy to be proven wrong.

`List<String> mock = mock(List.class);` won't ever compile without warning if `T mock(Class<T> t);`

and things like `<T, R extends T> R mock(Class<T> t` isn't what we need neither.

Why are you asking?

**Comment by ijuma** [comment]
I had to change a bunch of Scala test code in Kafka when upgrading to EasyMock 4.0.x due the the original change so this piqued my interest.

**Comment by ijuma** [comment]
I haven't tried 4.0.2 yet. :) I'm still unsure if this is an improvement over what we had in 3.x.
