### ISSUE TITLE
IllegalStateException for method with no arguments

### ISSUE THREAD

**Issue by bentatham** [easymock/easymock#238]
I am getting the `IllegalStateException` that 

```
This exception usually occurs when matchers are mixed with raw values when recording a method:
        foo(5, eq(6));  // wrong
You need to use no matcher at all or a matcher for every single param:
        foo(eq(5), eq(6));      // right
        foo(5, 6);      // also right
```

However, the only method being invoked does not have _any_ arguments at all, so I can't figure out what is going on.  Further, if I retry the same calls, it works fine.  

Encapsulated into a single method (with potentially infinite recursion):

```
private static Condition createConditionMetMock()
  {
    try
    {
      Condition condition = mock(Condition.class);
      expect(condition.isConditionMet()).andReturn(true).anyTimes();
      replay(condition);
      return condition;
    }
    catch (IllegalStateException e)
    {
      e.printStackTrace();
      return createConditionMetMock();
    }
  }
```

* When running just the class that has the call to this method, it never hits the exception.  Both in Eclipse and Maven with surefire.
* When I run my entire project (with Maven), it hits the exception (once) everytime.  This is weird because:
   * I have disabled parallel in surefire. `<parallel>none</parallel>`
   * My understanding, and looking at the code in `EasyMock`, everything my code should be thread local, and therefore not influenced by other threads even if this was the problem.

Context:
* Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T14:41:47-04:00)
* Java version: 1.8.0_191, vendor: Oracle Corporation
* maven-surefire-plugin 2.22.1

Any ideas what could be causing this?

**Comment by henri-tremblay** [comment]
Please have a look at the test right before. You probably have a pending parameter that was recorded but not consumed. It sometimes happens by mixing Hamcrest matchers with EasyMock ones.

**Comment by bentatham** [comment]
Indeed it is.  I've had this problem before, but it tended to be more obvious (in this case, it was easymock `anyObject` hidden inside a hamcrest `hasEntry`, which hamcrest happily accepted because it allows raw objects or `Matchers` to be passed to `hasEntry`).  

Perhaps this is yet another excuse to switch to assertj, or perhaps it has similar naming issues.

Thanks for the quick reply.

**Comment by henri-tremblay** [comment]
AssertJ rules!
