### ISSUE TITLE
JUnit 5 support (extension instead of EasyMockRunner)

### ISSUE THREAD

**Issue by tobymurray** [easymock/easymock#245]
As commented [here](https://github.com/easymock/easymock/issues/215#issuecomment-386077872), the JUnit 4 practice of `@RunWith(EasyMockRunner.class)` no longer works. `RunWith` has been [superseded by @ExtendWith](https://junit.org/junit5/docs/current/user-guide/#migrating-from-junit4-tips).

I haven't really looked at what that implies, is JUnit 5 compatibility for the same features on the roadmap?

A StackOverflow answer has a workaround here: https://stackoverflow.com/a/47243856/2152081 - is that viable as is?

**Comment by tobymurray** [comment]
I took the code from that StackOverflow answer and used it as described, it seems to work. I can submit a PR with that class if it'd be accepted?

**Comment by henri-tremblay** [comment]
Please do. Worst case is that I'll tweak it a little

**Comment by henri-tremblay** [comment]
Close by #246
