### ISSUE TITLE
Please comply with ASM license when re-distributing ASM

### ISSUE THREAD

**Issue by vlsi** [easymock/easymock#247]
ASM license specifies that `Redistributions of source code must retain the ... copyright notice`

I see that `easymock-4.0.2.jar` bundles ASM under `easymock-4.0.2.jar/uzip://org/easymock/asm` path, however it fails to retain the relevant copyright notice.

Would you please comply with ASM license? (see https://gitlab.ow2.org/asm/asm/blob/e246de13a995837bc88777aca47f141d9bcbfc01/LICENSE.txt )

Thanks.

See also:
* https://github.com/raphw/byte-buddy/issues/709
* https://gitlab.ow2.org/asm/asm/issues/317881

**Comment by henri-tremblay** [comment]
Hi. Strange. The maven-shade-plugin should do it. I'll check. Thanks and sorry about that.

**Comment by henri-tremblay** [comment]
That's why it doesn't work... The license is not in the jar. So I've added it manually in a directory dedicated to third-party licenses. It should be alright.
