### ISSUE TITLE
Allow @Mock to get a default name from the variable being mocked

### ISSUE THREAD

**Issue by sazzer** [easymock/easymock#260]
Currently, if I'm using `EasyMockRunner` / `EasyMockRule` and the `@Mock` annotation, I have the choice of using `@Mock(name = "xxx")` or else having an unnamed mock.

This works, but it means that if I'm mocking two different fields with the same type then I have to explicitly give them names or else the logs get confusing.

It would be relatively easy for this to instead use the field name as the default name for the mock, so that the only time you need to specify the `name="xxx"` is if you actually want a different value - which is probably rare.

Effectively it means that:
```
@Mock(name = "mockService")
private Service mockService;
```

just becomes:
```
@Mock
private Service mockService;
```

but still does the exact same thing.

**Comment by henri-tremblay** [comment]
Not a bad idea. However it forces a name on the mock. But still not a bad idea. I'll check but I would love a PR.

**Comment by sazzer** [comment]
Is forcing a name on the mock a bad idea? I couldn't see any problems with
that, but I struggle a bit to work out what the name actually did apart
from appear in the logs.

Cheers
-- 
Graham Cox

**Comment by henri-tremblay** [comment]
You are right. The name is only used to tell which mock is which when there is an error. However, if I use the field, it might make the message stranger because instead of talking about the class mocked it will be the field (but yes, I can use both to have a cute message).

**Comment by henri-tremblay** [comment]
The name will be "EasyMock for field x.y.z.IMethod.field"
