### ISSUE TITLE
Concat csv values using groovy script. 

### ISSUE THREAD

**Issue by justexecutee** [easymock/easymock#273]
Hi Experts, 

I have a csv file which has only 1 field. I need to concat the fields with a comma (,). Its a very simple requirement, however after writing the below code, it throws error mentioned:

Input
12
45
78

Output
12,45,78 

Code :
	import com.sap.gateway.ip.core.customdev.util.Message;
	import java.util.HashMap;
	def Message processData(Message message) {
    	//Body 
     	def body = message.getBody();
       	output = body.readLines().join(',')
       	message.setBody(output);
       	return message; 

Error : No signature of method: java.io.ByteArrayOutputStream.readLines() is applicable for argument types: () values: []

**Comment by henri-tremblay** [comment]
How is this related to EasyMock?
