### ISSUE TITLE
cglib dependency missing from documentation and Maven Central pom.xml

### ISSUE THREAD

**Issue by ebickle** [easymock/easymock#275]
During an upgrade from an older version of cglib, we followed the documentation at https://easymock.org/user-guide.html and easymock 4.3 via Maven Central (`<groupId>org.easymock</groupId><artifactId>easymock</artifactId><version>4.3</version>`).

We immediately ran into the error `java.lang.NoClassDefFoundError: net/sf/cglib/proxy/Enhancer`, indicating that EasyMock has an possible dependency on cglib that's missing from both the documentation and Maven Central pom.xml.

What's a bit confusing is that I can see the dependency listed in the [GitHub source code pom.xml](https://github.com/easymock/easymock/blob/easymock-4.0/core/pom.xml) but not the [Maven Central pom.xml](https://repo1.maven.org/maven2/org/easymock/easymock/4.3/easymock-4.3.pom).  

Any idea what's going on? Is the documentation and Maven Central pom.xml wrong, or are we using it incorrectly somehow and creating a dependency on cglib elsewhere in our unit tests?

**Comment by bgooren** [comment]
Hi! You can see here (https://github.com/easymock/easymock/blob/easymock-4.0/core/pom.xml#L126) that cglib is shaded, which means it is relocated inside easymock (to hide the dependency).

So you shouldn't be getting that exception when using easymock.

Can you add a stacktrace?

**Comment by ebickle** [comment]
It's been awhile, but I suspect what might have happened is that a conflict in a dependency was bringing over a different version of easymock. Whatever it was, we have things stable at the moment so I'll close out this issue. If it happens again I'll see if I can reproduce with more details and a stack trace.
