### ISSUE TITLE
java.lang.NullPointerException at org.easymock.internal.ClassProxyFactory.classPackage(ClassProxyFactory.java:178)

### ISSUE THREAD

**Issue by garydgregory** [easymock/easymock#343]
Over at Apache Commons Email, we hit an NPE updating from 4.3 to 5.0.1:

java.lang.NullPointerException
	at org.easymock.internal.ClassProxyFactory.classPackage(ClassProxyFactory.java:178)

See https://github.com/apache/commons-email/pull/111

**Comment by henri-tremblay** [comment]
I see the first test is using PowerMock. Could it be the problem?

**Comment by garydgregory** [comment]
It seems to me like some compatibility issue if the only change in the PR is changing the easymock version. Is compatibility not supported from 4.3 to 5.0.1?

**Comment by garydgregory** [comment]
Hi @henri-tremblay 
Did you get a chance to take a look?

**Comment by henri-tremblay** [comment]
Not yet.

**Comment by henri-tremblay** [comment]
I am able to reproduce locally. Not let's see why it happens.

**Comment by garydgregory** [comment]
Thank you @henri-tremblay

**Comment by garydgregory** [comment]
@henri-tremblay 
Hm, the CI is failing https://github.com/easymock/easymock/actions/runs/3808898724

**Comment by henri-tremblay** [comment]
Release is done and problem should be fixed in EasyMock 5.1.0
