### ISSUE TITLE
pom file error: the source.jar is not deployed correctly to maven

### ISSUE THREAD

**Issue by lijinliangyihao** [easymock/easymock#369]
Before, this plugin's goal is jar:
```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-source-plugin</artifactId>
    <executions>
        <execution>
            <id>attach-sources</id>
            <goals>
            <goal>jar</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```
but now, it's `jar-no-fork`, and I can't download the source of easy mock(the sources only contains asm and bytebuddy)
I think the goal should be `jar`, not `jar-no-fork`.

**Comment by henri-tremblay** [comment]
I had the problem as well. I think jar-no-fork was causing another issue. But I will look at it.
