### ISSUE TITLE
LinkageError when mocking certain classes

### ISSUE THREAD

**Issue by bindungszustandsamplitude** [easymock/easymock#373]
Hello together,

since EasyMock 5.1.0, I get a LinkageError when I try to create a mock for certain classes. I saw it first for javax.security classes such as `LoginContext`. In version 5.0.1, this worked without an issue.

**Step to reproduce:**
It could be reproduced by the following dummy test:
```java
@Test
void test() {
    EasyMock.mock(javax.security.auth.login.LoginContext.class);
}
```

**Expected behaviour:**
A mock for the class `LoginContext` gets created.

**Actual behaviour**
An exception with the following cause is thrown:
```
java.lang.LinkageError: bad field type alias: class org.easymock.internal.ClassMockingData not visible from class javax.security.auth.login.LoginContext$$$EasyMock$1
```

**EasyMock Version:** 5.1.0
**Java version:** Temurin 11 for macOS (`OpenJDK11U-jdk_aarch64_mac_hotspot_11.0.18_10`)

**Comment by henri-tremblay** [comment]
Yes. It's fixed with #356. Should release soon when I have 2 minutes.

**Comment by dmatej** [comment]
Just FYI, I have the same issue with the InitialContext on 5.1.0.
```
        mockSupport = new EasyMockSupport();
        initialContext = mockSupport.createMock(InitialContext.class);
```
I can confirm that with 5.2.0-SNAPSHOT ( 264a75dadbabe36fca2cfca903a240f327f6deda ) works well. When can we expect the release?

**Comment by arjantijms** [comment]
A release would be great indeed, thanks in advance!
