### ISSUE TITLE
Suspicious code in org.easymock.internal.ReplayState#invoke(Invocation)

### ISSUE THREAD

**Issue by toby1984** [easymock/easymock#448]
Just something I came across while stepping through a unit test, trying to understand why mocking an interface seems to screw up a default method that's not been overridden.

Code looks like a typo, the conditional should probably be inverted.

![image](https://github.com/easymock/easymock/assets/271364/b948b618-98f9-4bfa-ab07-1f26d051d127)

**Comment by henri-tremblay** [comment]
No. It's normal. When a mock is thread-safe, it will lock around the invocation to prevent another thread from messing with the mock. However, this is slower than not doing anything and can also change the original object behavior by excessive locking. So it's possible to have a not thread-safe mock that is then expected to be used in only one thread.

These are weird use-cases I know but they were requested a long time ago.
