### ISSUE TITLE
Migrating from easymock 2.X to 5.x .org.easymock.MockControl is not found

### ISSUE THREAD

**Issue by bishtjagmohan** [easymock/easymock#451]
We have codes using org.easymock.MockControl but it's gone from 3.x onwards. What's the replacement for this?

**Comment by henri-tremblay** [comment]
What is the code?

**Comment by bishtjagmohan** [comment]
MockControl.createControl( clazz ) , control.verify() and many others. I see that it's stated to use EasyMock's static methods instead of these . But looking for like to like replacement for minimal change.

**Comment by bishtjagmohan** [comment]
There were calls like
setDefaultReturnValue(Object value)

**Comment by bishtjagmohan** [comment]
There are calls like
setDefaultReturnValue(Object value), MockControl.createControl(Class<T> toMock) which doesn't have similar methods with same signatures as replacements.

**Comment by henri-tremblay** [comment]
No. They were removed since they felt not that useful.
I am waiting for someone to demonstrate a useful use case to add them back.

**Comment by henri-tremblay** [comment]
I will close this since I do not feel there is a need to support it right now.
