### ISSUE TITLE
@Mock default name is not used in failure messages

### ISSUE THREAD

**Issue by sloescape** [easymock/easymock#520]
Although @Mock usefully generates a default name for a mock using the field name, this name is not used when reporting failures, for example in verify failures.   The issue is in Invocation.getMockAndMethodName which does not use the generated name for the mock if it does not look like a java identifier,  which the generated name does not.   As a result I believe the value of the @Mock facility is reduced because it requires the manual addition of a 'name' attribute to differentiate mocks of the same type which in almost all cases will be the same as the field name.

**Comment by henri-tremblay** [comment]
But a field name should be a Java identifier no?

**Comment by sloescape** [comment]
It is the generated mock name that does not pass the check for a valid java identifier.  Invocation.getMockAndMethodName has 'String mockName = mock.toString();' which gives a default mockName of "EasyMock for ...." which is not a valid java identifier as it include space characters.

**Comment by henri-tremblay** [comment]
Can you give me a quick test case for that? Because I remember changing something in that realm. So maybe it's fixed now.

**Comment by henri-tremblay** [comment]
Thank you. I'm working on it. I see what you mean.
