### ISSUE TITLE
 class org.easymock.internal.ClassMockingData not visible from class com.sun.net.httpserver.HttpExchange$$$EasyMock$1

### ISSUE THREAD

**Issue by tpummer** [easymock/easymock#559]
I've created a minimal showcase, using jdk17 EasyMock 5.2.0 resulting with an error similar to #373 and #515:

```
Caused by: java.lang.LinkageError: bad field type alias: class org.easymock.internal.ClassMockingData not visible from class com.sun.net.httpserver.HttpExchange$$$EasyMock$1
```
on mocking _com.sun.net.httpserver.HttpExchange_

```
    @Test()
    public void test() {
        EasyMock.mock(com.sun.net.httpserver.HttpExchange.class);
    }
```

You can find the source here on github under https://github.com/tpummer/EasyMockErrorShowCase
[error_without_add_opens.txt](https://github.com/tpummer/EasyMockErrorShowCase/blob/main/error_without_add_opens.txt) contains the log on running mvn clean install
[error_add_opens.txt](https://github.com/tpummer/EasyMockErrorShowCase/blob/main/error_add_opens.txt) the log on running mvn clean install with --add-opens params
[test.txt](https://github.com/tpummer/EasyMockErrorShowCase/blob/main/test.txt) contians the log running the test in intellij

**Comment by henri-tremblay** [comment]
Fixed by #373
