### ISSUE TITLE
Possible Null Pointer Dereference in Result.java

### ISSUE THREAD

**Issue by ZuhairORZaki** [easymock/easymock#670]
# Reporting a bug found by iCR

In file: [Result.java](https://github.com/easymock/easymock/blob/master/core/src/main/java/org/easymock/internal/Result.java#L83), there is a potential case of null pointer dereference. In method `answer` inside class `DelegatingAnswer`, there is a call to `LastControl.getCurrentInvocation()` which returns an object of type `Invocation`. Later that object is referenced in `invocation.getMethod()`. 

```java
     public Object answer() throws Throwable {
          Invocation invocation = LastControl.getCurrentInvocation();
          try {
          Method m = invocation.getMethod();
```

But `LastControl.getCurrentInvocation()` can return null if `stack` which is of type `List<Invocation>` is itself null or an empty list.

```java
    public static Invocation getCurrentInvocation() {
        List<Invocation> stack = threadToCurrentInvocation.get();
        if (stack == null || stack.isEmpty()) {
            return null;
        }
        return stack.get(stack.size()-1);
    }
```

If that happens it will cause a `NullPointerException`.

It is not immediately clear whether the list would always be non-empty before any call to `answer` method. In that case fixing it might seem unnecessary, but still it is good practice to not assume anything about data coming from outside a class.

### Possible Fix
One way to handle it would be adding a new `catch` clause for `NullPointerException`.

```diff
--- /workspace/source/core/src/main/java/org/easymock/internal/Result.java
+++ /workspace/source/core/src/main/java/org/easymock/internal/Result.java
@@ -79,7 +79,18 @@

     public Object answer() throws Throwable {
          Invocation invocation = LastControl.getCurrentInvocation();
          try {
          Method m = invocation.getMethod();
          if(!m.isAccessible()) {
               m.setAccessible(true);
          }
          return m.invoke(value, convertVarargs(m, invocation.getArguments()));
          } catch (IllegalArgumentException e) {
          throw new IllegalArgumentException("Delegation to object [" + value
                    + "] is not implementing the mocked method [" + invocation.getMethod() + "]", e);
          } catch (InvocationTargetException e) {
          throw e.getCause();
          }
+         catch (NullPointerException e) {
+         throw e.getCause();
+         }

     }
```

### Sponsorship and Support:
This work is done by the security researchers from OpenRefactory and is supported by the [Open Source Security Foundation (OpenSSF)](https://openssf.org/): [Project Alpha-Omega](https://alpha-omega.dev/). Alpha-Omega is a project partnering with open source software project maintainers to systematically find new, as-yet-undiscovered vulnerabilities in open source code - and get them fixed - to improve global software supply chain security.

The bug is found by running the iCR tool by [OpenRefactory, Inc.](https://openrefactory.com/) and then manually triaging the results.

**Comment by henri-tremblay** [comment]
Since this is automated it seems, my comment is the following: The fix is pretty bad. Catching the NPE to return the non-existing cause is a bad idea. The issue is unlikely but someone really working out of the normal mocking pattern could cause it. I will provide a fix.

**Comment by ZuhairORZaki** [comment]
Sorry about the suggested fix. I agree it was pretty awkward. The fix presented here is just a Gen-AI based suggestion given by our tool. I should have explained it better that in no way we were suggesting implementing this exact fix. The actual fix will always depend on the requirements and intention behind the code.

Anyway, thanks a lot for looking into this and fixing the bug.
