### ISSUE TITLE
easymock.org unresolvable 

### ISSUE THREAD

**Issue by jkahrman** [easymock/easymock#698]
easymock.org appears to have been unresolvable since at least Nov 8th. The Internet Archive was capturing snapshots every couple of weeks up until Oct 1st, 2024, so it may have been down anytime after that. https://web.archive.org/web/20240000000000*/Easymock.org

Sorry to report what appears to be a DNS registration issue via the source control of the project, but I didn’t find any better contact channels.

**Comment by henri-tremblay** [comment]
Thanks a lot for the report!

**Comment by henri-tremblay** [comment]
Back on.
